bash failure_tests_with_param.sh 0 0 0 0 || exit 1 
bash failure_tests_with_param.sh 1 0 0 0 || exit 1
bash failure_tests_with_param.sh 0 1 0 0 || exit 1
bash failure_tests_with_param.sh 0 0 1 0 || exit 1
bash failure_tests_with_param.sh 0 0 0 1 || exit 1
bash failure_tests_with_param.sh 1 1 0 0 || exit 1
bash failure_tests_with_param.sh 1 0 1 0 || exit 1
bash failure_tests_with_param.sh 1 0 0 1 || exit 1
bash failure_tests_with_param.sh 0 1 1 0 || exit 1
bash failure_tests_with_param.sh 0 1 0 1 || exit 1
bash failure_tests_with_param.sh 0 0 1 1 || exit 1
bash failure_tests_with_param.sh 0 1 1 1 || exit 1
bash failure_tests_with_param.sh 1 0 1 1 || exit 1
bash failure_tests_with_param.sh 1 1 0 1 || exit 1
bash failure_tests_with_param.sh 1 1 1 0 || exit 1
