// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#![cfg_attr(feature = "mesalock_sgx", no_std)]
#[cfg(feature = "mesalock_sgx")]
#[macro_use]
extern crate sgx_tstd as std;

use serde::{Deserialize, Serialize};
use std::prelude::v1::*;

#[derive(thiserror::Error, Debug)]
pub enum AttestationError {
    #[error("OCall error")]
    OCallError,
    #[error("Attestation Service error")]
    AttestationServiceError,
    #[error("Platform error")]
    PlatformError,
    #[error("Report error")]
    ReportError,
}

pub enum AttestationConfig {
    NoAttestation,
    WithAttestation(AttestationServiceConfig),
}

pub(crate) enum AttestationAlgorithm {
    SgxEpid,
    SgxEcdsa,
}

pub struct AttestationServiceConfig {
    algo: AttestationAlgorithm,
    as_url: url::Url,
    api_key: String,
    spid: sgx_types::sgx_spid_t,
}

pub struct DcapConfig {}

impl AttestationConfig {
    pub fn new(algorithm: &str, url: &str, api_key: &str, spid_str: &str) -> Self {
        if cfg!(sgx_sim) {
            return Self::NoAttestation;
        }

        use core::convert::TryFrom;

        let mut spid = sgx_types::sgx_spid_t::default();
        let hex = hex::decode(spid_str).expect("Illegal SPID provided");
        spid.id = <[u8; 16]>::try_from(hex.as_slice()).expect("Illegal SPID provided");

        let algo = match algorithm {
            "sgx_epid" => AttestationAlgorithm::SgxEpid,
            "sgx_ecdsa" => AttestationAlgorithm::SgxEcdsa,
            _ => panic!("Unsupported remote attestation algorithm"),
        };

        let att_service_cfg = AttestationServiceConfig {
            algo,
            as_url: url::Url::parse(url).unwrap(),
            api_key: api_key.to_string(),
            spid,
        };

        Self::WithAttestation(att_service_cfg)
    }
}

// AttestationReport can be endorsed by either the Intel Attestation Service
// using EPID or Data Center Attestation Service (platform dependent) using
// ECDSA.
#[derive(Default, Serialize, Deserialize)]
pub(crate) struct EndorsedAttestationReport {
    // Attestation report generated by the hardware
    pub report: Vec<u8>,
    // Singature of the report
    pub signature: Vec<u8>,
    // Certificate matching the signing key of the signature
    pub signing_cert: Vec<u8>,
}

#[macro_use]
mod cert;
pub mod report;
pub mod verifier;

cfg_if::cfg_if! {
    if #[cfg(feature = "mesalock_sgx")]  {
        mod service;
        mod key;
        mod platform;
        mod attestation;
        pub use attestation::RemoteAttestation;
    }
}
